name: Build, Push to Docker Hub, and Deploy to ClawCloud

on:
  push:
    branches:
      - gesture-ml-production

env:
  IMAGE_NAME: maze-game
  IMAGE_TAG: latest

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest testing/test.py

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG .

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG

      - name: Deploy to ClawCloud via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CLAW_HOST }}
          username: ${{ secrets.CLAW_USERNAME }}
          key: ${{ secrets.CLAW_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG

            docker stop $IMAGE_NAME || true
            docker rm $IMAGE_NAME || true

            docker run -d -p 80:8000 --name $IMAGE_NAME ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG
